on:
  push:
    branches:
      - 'main'

permissions:
    contents: write
    packages: write

jobs:
  releases-matrix:
    name: compile binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows]
        goarch: [amd64]
    steps:
    - uses: actions/checkout@v4
    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: "1.24.1"
        binary_name: "go-wisp"
        extra_files: config.json
        compress_assets: zip
        ldflags: -s -w
        md5sum: false
        release_tag: builds
        asset_name: go-wisp-${{ matrix.goos }}
        overwrite: true